"""Contratos de persistência. Toda consulta é escopada por tenant."""

from datetime import datetime, timedelta
from typing import Protocol
from uuid import UUID

from app.domain.entities import (
    FaceRegistration,
    LivenessChallenge,
    LivenessSession,
    Subject,
    Tenant,
    Verification,
    VerificationEvent,
    WebhookDelivery,
)


class TenantRepository(Protocol):
    async def get_by_api_key_hash(self, api_key_hash: str) -> Tenant | None: ...
    async def get(self, tenant_id: UUID) -> Tenant | None: ...
    async def get_by_slug(self, slug: str) -> Tenant | None: ...
    async def add(self, tenant: Tenant) -> None: ...
    async def save(self, tenant: Tenant) -> None: ...


class SubjectRepository(Protocol):
    async def get_by_external_id(self, tenant_id: UUID, external_id: str) -> Subject | None: ...
    async def get(self, tenant_id: UUID, subject_id: UUID) -> Subject | None: ...
    async def add(self, subject: Subject) -> None: ...


class FaceRegistrationRepository(Protocol):
    async def get(self, registration_id: UUID) -> FaceRegistration | None: ...
    async def get_for_tenant(
        self, tenant_id: UUID, registration_id: UUID
    ) -> FaceRegistration | None: ...
    async def get_latest_for_subject(
        self, tenant_id: UUID, subject_id: UUID
    ) -> FaceRegistration | None: ...
    async def get_active_for_subject(
        self, tenant_id: UUID, subject_id: UUID
    ) -> FaceRegistration | None: ...
    async def save(self, registration: FaceRegistration) -> None: ...


class VerificationRepository(Protocol):
    async def get(self, verification_id: UUID) -> Verification | None: ...
    async def get_for_tenant(
        self, tenant_id: UUID, verification_id: UUID
    ) -> Verification | None: ...
    async def get_by_idempotency_key(
        self, tenant_id: UUID, idempotency_key: str
    ) -> Verification | None: ...
    async def save(self, verification: Verification) -> None: ...


class WebhookDeliveryRepository(Protocol):
    async def add(self, delivery: WebhookDelivery) -> None: ...
    async def claim_due(self, now: datetime, lease: timedelta, limit: int) -> list[WebhookDelivery]:
        """Reserva entregas PENDING vencidas, sem bloquear outro worker (SKIP LOCKED)."""
        ...

    async def save(self, delivery: WebhookDelivery) -> None: ...


class LivenessChallengeRepository(Protocol):
    async def add(self, challenge: LivenessChallenge) -> None: ...
    async def get_for_tenant(
        self, tenant_id: UUID, challenge_id: UUID, *, for_update: bool = False
    ) -> LivenessChallenge | None: ...
    async def get(self, challenge_id: UUID) -> LivenessChallenge | None: ...
    async def save(self, challenge: LivenessChallenge) -> None: ...


class LivenessSessionRepository(Protocol):
    async def add(self, session: LivenessSession) -> None: ...


class VerificationEventRepository(Protocol):
    async def add(self, event: VerificationEvent) -> None: ...


class UnitOfWork(Protocol):
    tenants: TenantRepository
    subjects: SubjectRepository
    face_registrations: FaceRegistrationRepository
    verifications: VerificationRepository
    liveness_sessions: LivenessSessionRepository
    liveness_challenges: LivenessChallengeRepository
    events: VerificationEventRepository
    webhook_deliveries: WebhookDeliveryRepository

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, *exc: object) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
